/** Molden format writer for molecular orbital visualization.
 *
 *  Generates [Atoms], [GTO], [MO] sections.
 *  Coordinates in Angstrom. MO coefficients in atom-sequential basis order.
 *
 *  Supports RHF (Occup=2/0), ROHF (Occup=2/1/0), and UHF (Alpha+Beta sections).
 */

import type { Atom } from './types';
import { atomicNumberToElementName, BOHR_TO_ANGSTROM } from './constants';
import type { BasisSet } from './basisSet';
import type { Matrix, FloatArray } from '../linalg/matrix';

export interface MoldenOptions {
  atoms: Atom[];
  basisSet: BasisSet;
  numBasis: number;
  // Alpha (or shared for RHF/ROHF) orbitals
  coefficients: Matrix;
  orbitalEnergies: FloatArray;
  numOccupied: number;         // number of alpha-occupied orbitals
  // Beta orbitals (UHF: separate coefficients; ROHF: numOccupiedBeta only)
  coefficientsBeta?: Matrix;
  orbitalEnergiesBeta?: FloatArray;
  numOccupiedBeta?: number;
}

export function writeMolden(opts: MoldenOptions): string {
  const {
    atoms, basisSet, numBasis,
    coefficients, orbitalEnergies, numOccupied,
    coefficientsBeta, orbitalEnergiesBeta, numOccupiedBeta,
  } = opts;
  const lines: string[] = [];

  // Header
  lines.push('[Molden Format]');
  lines.push('[Title]');
  lines.push('Generated by GANSU Lite');
  lines.push('');

  // [Atoms] section (Angstrom)
  lines.push('[Atoms] Angs');
  for (let i = 0; i < atoms.length; i++) {
    const a = atoms[i];
    const elem = atomicNumberToElementName(a.atomicNumber);
    const x = (a.coordinate.x * BOHR_TO_ANGSTROM).toFixed(8);
    const y = (a.coordinate.y * BOHR_TO_ANGSTROM).toFixed(8);
    const z = (a.coordinate.z * BOHR_TO_ANGSTROM).toFixed(8);
    lines.push(`${elem}  ${i + 1}  ${a.atomicNumber}  ${x}  ${y}  ${z}`);
  }
  lines.push('');

  // [GTO] section
  lines.push('[GTO]');
  for (let i = 0; i < atoms.length; i++) {
    const elem = atomicNumberToElementName(atoms[i].atomicNumber);
    const ebs = basisSet.get(elem);
    lines.push(`  ${i + 1} 0`);
    for (const cg of ebs.contractedGausses) {
      lines.push(`${cg.type.toLowerCase()}   ${cg.primitives.length}  1.00`);
      for (const p of cg.primitives) {
        lines.push(`  ${p.exponent.toExponential(10)}  ${p.coefficient.toExponential(10)}`);
      }
    }
    lines.push('');
  }

  // [MO] section
  lines.push('[MO]');

  const isUHF = coefficientsBeta != null && orbitalEnergiesBeta != null;

  if (isUHF) {
    // UHF: alpha MOs then beta MOs, Occup = 1.0 or 0.0
    for (let mo = 0; mo < numBasis; mo++) {
      lines.push(`Sym=   A`);
      lines.push(`Ene= ${orbitalEnergies[mo].toFixed(10)}`);
      lines.push(`Spin= Alpha`);
      lines.push(`Occup= ${mo < numOccupied ? '1.000000' : '0.000000'}`);
      for (let mu = 0; mu < numBasis; mu++) {
        lines.push(`  ${mu + 1}  ${coefficients.get(mu, mo).toExponential(10)}`);
      }
    }
    const nOccBeta = numOccupiedBeta ?? 0;
    for (let mo = 0; mo < numBasis; mo++) {
      lines.push(`Sym=   A`);
      lines.push(`Ene= ${orbitalEnergiesBeta![mo].toFixed(10)}`);
      lines.push(`Spin= Beta`);
      lines.push(`Occup= ${mo < nOccBeta ? '1.000000' : '0.000000'}`);
      for (let mu = 0; mu < numBasis; mu++) {
        lines.push(`  ${mu + 1}  ${coefficientsBeta!.get(mu, mo).toExponential(10)}`);
      }
    }
  } else {
    // RHF or ROHF: single set of MOs
    // RHF: Occup = 2.0 / 0.0
    // ROHF: Occup = 2.0 (doubly) / 1.0 (singly) / 0.0 (virtual)
    const nOccBeta = numOccupiedBeta ?? numOccupied; // RHF: beta = alpha
    for (let mo = 0; mo < numBasis; mo++) {
      lines.push(`Sym=   A`);
      lines.push(`Ene= ${orbitalEnergies[mo].toFixed(10)}`);
      lines.push(`Spin= Alpha`);
      let occup: string;
      if (mo < nOccBeta) occup = '2.000000';        // doubly occupied
      else if (mo < numOccupied) occup = '1.000000'; // singly occupied (ROHF)
      else occup = '0.000000';                        // virtual
      lines.push(`Occup= ${occup}`);
      for (let mu = 0; mu < numBasis; mu++) {
        lines.push(`  ${mu + 1}  ${coefficients.get(mu, mo).toExponential(10)}`);
      }
    }
  }

  return lines.join('\n');
}
